日本語ドキュメントの追加
0xhokusai/hokusai-api-docs pull request #10
Opened 2021-08-11 08:11 UTC by wan-nyan-wan

## やったこと

- 日本語ドキュメントの暫定完成版

## やらないこと

- 英語ドキュメントの整備

## 動作確認

- `yarn start`をしてドキュメントの内容を確認してください

2021-08-11 15:21 UTC, fu31 commented
![image](https://user-images.githubusercontent.com/27881355/129056693-9f8544c6-e482-4ef0-b519-a42f0e16543d.png)
一点だけ、nftをmintするページとroyaltyを設定するページの改行がうまく行かずレイアウト崩れているところがありました！
（大したところではないですが、、、）

2021-08-11 15:22 UTC, fu31 commented
ざっと見た感じ他のところは問題なさそうです。細かいところは明日確認します🙇

2021-08-12 05:51 UTC, yuta-tsurusaki requested changes
ありがとうございます！いい感じですね！

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/authentication.mdx
> +認証のための API Key 発行については、[TODO](./) を確認してください。
このTODOは後日API Key発行についてのページを作って、そこのリンクを貼るという認識であってますか？

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/get.mdx
> +  };
```suggestion
const baseUrl = "https://api.hokusai.app"

const getNft = async (baseUrl, apiKey, contractId, tokenId) => {
  const path = `/v1/nfts/${contractId}/${tokenId}`
  const url = new URL(baseUrl + path);

  const params = {
    key: apiKey
  };
```
jsなのでcamel case統一で行きましょう！
他のendpointも確認してもらえると〜

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/get.mdx
> +  path = f"/v1/nfts/{contractId}/{tokenId}"
```suggestion
def get_nft(base_url: str, api_key: str, contract_id: str, token_id: str):
  path = f"/v1/nfts/{contract_id}/{token_id}"
```
ここは好み分かれそうですが、pathパラメータなので個人的にはsnake caseで行くかなという趣味です

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/get.mdx
> +|キー|型|値の例|説明|
pathに関しては"キー"ではなく"パラメータ"の方が語弊がないかもしれません。

参考: [LINE Blockchain - APIガイド サービス情報を取得する](https://docs-blockchain.line.biz/ja/api-guide/category-services?id=v1-services-serviceid-get)
![Screen Shot 2021-08-12 at 14 29 58](https://user-images.githubusercontent.com/45069709/129143308-421e9eeb-2fb5-42e6-b4c3-b89fd2a2fa45.png)

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/get.mdx
> +|キー|型|値の例|説明|
あと全体的な話ですがRequiredカラムがある方が良い気がしました。
といっても全部Requiedですが...

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/mint.mdx
> +  };
```suggestion
  const requestBody = {
    to,
    tokenUri,
  };
```
jsではkey名とvalueの変数名が一緒ならvalueの記述を省略できるのでこっちが自然かなと思いました
あとはcamelcaseですね

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/mint.mdx
> +  path = f"/v1/nfts/{contractId}/mint"
```suggestion
def mint_nft(base_url: str, api_key: str, contract_id: str, to: str, tokenUri: str):
  path = f"/v1/nfts/{contract_id}/mint"
```
これも趣味です。request bodyのjsonなどでkeynameをcamel caseにしたいという特別な理由がない限りはsnakeにする気がします...が判断はおまかせします。

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/royalty/get.mdx
> +|`percentage`|number|`10`|ロイヤリティの割合（0~100%)|
これは最近発覚した&実装した仕様なのですが、0-100で小数第二位までパーセンテージ決めれる仕様になっていて、小数第二位以下は四捨五入されます。
上記追加いただけると嬉しいです！

2021-08-12 05:51 UTC, yuta-tsurusaki commented on docs/nft/mint.mdx
> +NFT を [Mint](/glosarry#mint)します。
用語集へのリンクいいですね！

2021-08-12 05:55 UTC, wan-nyan-wan commented on docs/authentication.mdx
> +認証のための API Key 発行については、[TODO](./) を確認してください。
その通りです。まだ設定URLとか無いですよね？

2021-08-12 05:58 UTC, yuta-tsurusaki commented
あとこれは本prから離れる&重要度は高くないのですが、トップページの見た目が微妙かなと思いました。
デザインの話になるので無視してもらってもいいのですが、とりあえず共有しておきます。

![Screen Shot 2021-08-12 at 14 13 28](https://user-images.githubusercontent.com/45069709/129145013-6b2ed42c-d216-4642-8324-53d7940d80eb.png)

理由としては、**footerの主張が激しすぎて一番重要なところがパッと見で分からない** のが原因かなと思っていまして、
- footerのiconを小さくする
- footerの縦幅を小さくする
- このページのbodyにパッと目を引くようなコンテンツをいれる
  - https://0xhokusai.medium.com/ や https://www.notion.so/Press-kit-a63793d2d038449e9b2edbac220f9554 のロゴなどを使うと良いかもしれません。自分だったら以下の画像をはめてみて、主張が激しすぎたら背景を無地にして調節するかなという感じです。

![image](https://user-images.githubusercontent.com/45069709/129145492-ec534192-7b50-4371-acda-317b38a30d83.png)

2021-08-12 06:03 UTC, yuta-tsurusaki commented on docs/authentication.mdx
> +認証のための API Key 発行については、[TODO](./) を確認してください。
ないです！が、多分設定URLが出来る前にこのドキュメントを公開することになるので、
Hokusai API運営にお問い合わせください的な文言がいいかもしれません。（管理画面等が出来るまでは実際そういう運用になるはずです）

2021-08-12 14:24 UTC, wan-nyan-wan commented on docs/nft/get.mdx
> +|キー|型|値の例|説明|
required columnを追加しました！

2021-08-12 14:30 UTC, wan-nyan-wan commented
> あとこれは本prから離れる&重要度は高くないのですが、トップページの見た目が微妙かなと思いました。
> デザインの話になるので無視してもらってもいいのですが、とりあえず共有しておきます。
> 
> ![Screen Shot 2021-08-12 at 14 13 28](https://user-images.githubusercontent.com/45069709/129145013-6b2ed42c-d216-4642-8324-53d7940d80eb.png)
> 
> 理由としては、**footerの主張が激しすぎて一番重要なところがパッと見で分からない** のが原因かなと思っていまして、以下が解決策です。
> 
>     * footerのiconを小さくする
> 
>     * footerの縦幅を小さくする
> 
>     * このページのbodyにパッと目を引くようなコンテンツをいれる
>       
>       * https://0xhokusai.medium.com/ や https://www.notion.so/Press-kit-a63793d2d038449e9b2edbac220f9554 のロゴなどを使うと良いかもしれません。自分だったら以下の画像をタイトルの下にはめてみて、主張が激しすぎたら背景を無地にして調節するかなという感じです。
> 
> 
> ![image](https://user-images.githubusercontent.com/45069709/129145492-ec534192-7b50-4371-acda-317b38a30d83.png)

僕もフッターのアイコンはでかいな...と思っていました。デザインを柔軟に変えたいのですが、フッターのデザインを柔軟に変えるためには、少し工数がかかります。現状、すぐにできる解決策はアイコンを消すことです。ですから、フッターのアイコンを消そうと思うんですがいかがでしょうか。

2021-08-12 14:35 UTC, wan-nyan-wan commented
> ![image](https://user-images.githubusercontent.com/27881355/129056693-9f8544c6-e482-4ef0-b519-a42f0e16543d.png)
> 一点だけ、nftをmintするページとroyaltyを設定するページの改行がうまく行かずレイアウト崩れているところがありました！
> （大したところではないですが、、、）

こちらの修正ですが、docusaurusのデザイン自体にテコ入れする必要があるので、修正に時間がかかりそうです。リリース後に直そうか悩んでいるのですがいかがでしょうか。

2021-08-12 14:38 UTC, wan-nyan-wan commented on docs/nft/get.mdx
> +  };
修正しました！

2021-08-12 14:41 UTC, wan-nyan-wan commented on docs/nft/get.mdx
> +  path = f"/v1/nfts/{contractId}/{tokenId}"
snake case で統一しました。

2021-08-13 09:55 UTC, fu31 reviewed
> > ![image](https://user-images.githubusercontent.com/27881355/129056693-9f8544c6-e482-4ef0-b519-a42f0e16543d.png)
> > 一点だけ、nftをmintするページとroyaltyを設定するページの改行がうまく行かずレイアウト崩れているところがありました！
> > （大したところではないですが、、、）
> 
> こちらの修正ですが、docusaurusのデザイン自体にテコ入れする必要があるので、修正に時間がかかりそうです。リリース後に直そうか悩んでいるのですがいかがでしょうか。

レビュー遅くなって申し訳ないです。
工数かかりますよね、、
一旦ここはリリース後でも良いかなと思います。

2021-08-13 10:18 UTC, merged