Add Document in English
0xhokusai/hokusai-api-docs pull request #16
Opened 2021-08-17 12:27 UTC by wan-nyan-wan

## やったこと

- 日本語ドキュメントの英訳した

## 動作確認

- `yarn build && yarn serve` 起動
- 日英を切り替えられることを確認
- 英訳が正しいか、文章の体裁を確認

2021-08-18 22:57 UTC, yuta-tsurusaki requested changes
いい感じですね！

2021-08-18 22:57 UTC, yuta-tsurusaki commented on i18n/en/docusaurus-plugin-content-docs/current/endpoint.mdx
> +In Hokusai API, you send a request to the following base URL.
"In Hokusai API"はくどいのと、baseURLが主語になってると直感的かなと思いました。参考にしたドキュメントでは結構端的に書いてるところが多そうですね。以下に参考になりそうな例も貼っておきます。

---

> The base URL to send all API requests is https://api.notion.com. HTTPS is required for all API requests.

https://developers.notion.com/reference/intro#conventions

---

> The base endpoint is: https://api.binance.com

https://binance-docs.github.io/apidocs/spot/en/#general-info

---

![Screen Shot 2021-08-19 at 7 28 06](https://user-images.githubusercontent.com/45069709/129980292-aa564e38-9897-4482-9123-2407b264c157.png)

https://stripe.com/docs/api

---

2021-08-18 22:57 UTC, yuta-tsurusaki commented on i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +Hokusai provides REST APIs. This document describes the Hokusai API specification.
完璧にRESTかと言われると怪しいので、
The Hokusai API is organized around REST. みたいな、厳密ではないよ感を出せるとより良いかもしれません。
参考: https://stripe.com/docs/api

2021-08-18 22:57 UTC, yuta-tsurusaki commented on i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +The Hokusai API allows NFT businesses of any size to publish, transmit, and perform secondary distribution fees for NFTs, and manage NFT businesses without the need for crypto assets.
```suggestion
The Hokusai API allows NFT businesses of any size to mint, transfer, and set royalty for NFTs, and manage NFT businesses without the need for crypto assets.
```
こっちのほうがシンプルかなと思いました、が、もしかするとmintはcrypto界隈特有の言い回しの可能性はあるので、publishの方がいいかもしれません。

2021-08-18 22:57 UTC, yuta-tsurusaki commented on i18n/en/docusaurus-plugin-content-docs/current/nft/get.mdx
> +|`contractId`|string|`ADXS6zyen4NctAjH`|`contractId` issued by Hokusa API|Required|
```suggestion
|`contractId`|string|`ADXS6zyen4NctAjH`|`contractId` issued by Hokusai API|Required|
```

2021-08-18 22:57 UTC, yuta-tsurusaki commented on i18n/en/docusaurus-plugin-content-docs/current/nft/mint.mdx
> +|`contractId`|string|`ADXS6zyen4NctAjH`|`contractId` issued by Hokusa API|Required|
```suggestion
|`contractId`|string|`ADXS6zyen4NctAjH`|`contractId` issued by Hokusai API|Required|
```

2021-08-18 22:57 UTC, yuta-tsurusaki commented on i18n/en/docusaurus-plugin-content-docs/current/royalty/set.mdx
> +|`contractId`|string|`ADXS6zyen4NctAjH`|`contractId` issued by Hokusa API|Required|
```suggestion
|`contractId`|string|`ADXS6zyen4NctAjH`|`contractId` issued by Hokusai API|Required|
```

2021-08-19 12:31 UTC, wan-nyan-wan commented on i18n/en/docusaurus-plugin-content-docs/current/endpoint.mdx
> +In Hokusai API, you send a request to the following base URL.
参考例までありがとうございます！修正しました。

2021-08-19 12:34 UTC, wan-nyan-wan commented on i18n/en/docusaurus-plugin-content-docs/current/intro.mdx
> +Hokusai provides REST APIs. This document describes the Hokusai API specification.
修正しました。

2021-08-19 14:02 UTC, yuta-tsurusaki approved these changes

2021-08-19 14:03 UTC, wan-nyan-wan commented
#20 の PR

2021-08-19 14:03 UTC, merged